version: "3.9"
services:

#MY SQL
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sasa
      MYSQL_DATABASE: msvc_usuarios
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring
      -
#MSVC_USUARIOS
  msvc-usuarios:
    container_name: msvc-usuarios
    image: frantu81/usuarios:latest
#    build:
#      context: ./
#      dockerfile: ./msvc-usuarios/Dockerfile
    ports:
      - "8001:8001"
    environment:
      PORT: 8001
      DB_HOST: mysql8:3306
      DB_DATABASE: msvc_usuarios
      DB_USERNAME: root
      DB_PASSWORD: sasa
      CURSOS_URL: DNS_DE_IP_PUBLICA_INSTANCIA_AWS_USUARIOS:8002
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always

#VOLUMES
volumes:
  data-mysql:
    name: data-mysql

#NETWORKS
networks:
  spring:
    name: spring